# Generated by Django 5.2.8 on 2025-11-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('single', '싱글'), ('double', '더블'), ('twin', '트윈'), ('family', '패밀리'), ('suite', '스위트')], max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('price_per_night', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(blank=True, to='rooms.amenity')),
            ],
        ),
    ]
